### ISSUE TITLE
[ENH] Add check for outdated link targets to CI

### ISSUE THREAD

**Issue by fabianegli** [bigbio/proteomics-sample-metadata#650]
The repository adopted the HTTPS network protocol for resources that provide it.

New entries might try to add FTP or HTTP resource links which does not comply with the newly adopted (can I say?) guideline.

**Comment by ypriverol** [comment]
See my comment (https://github.com/bigbio/proteomics-metadata-standard/issues/651#issuecomment-1115857506)
