### ISSUE TITLE
Instrument - timsTOF HT

### ISSUE THREAD

**Issue by Arthfael** [bigbio/proteomics-sample-metadata#700]
Looking at acceptable MS instrument models, the timsTOF HT is missing:

Bruker Daltonics timsTOF series (7)
    timsTOF
    timsTOF fleX
    timsTOF fleX MALDI-2
    timsTOF Pro
    timsTOF Pro 2
    timsTOF SCP
    timsTOF Ultra

Best,

Armel

**Comment by ypriverol** [comment]
We will be adding all the instruments in PSI-MS. @deeptijk Can you take a look to it.

**Comment by ypriverol** [comment]
Dear @Arthfael we added the timsTOF HT to the ontology, you can use now MS:1003404.

**Comment by Arthfael** [comment]
Thanks!
