### ISSUE TITLE
What ontology should values under the header characteristics[disease] fall into?

### ISSUE THREAD

**Issue by cclark1e** [bigbio/proteomics-sample-metadata#724]
What ontology should values under the header characteristics[disease] fall into? E.g. should they be diseases from the Human Disease Ontology?

Or am I misunderstanding, and this is not controlled?

Thanks a lot
Charlie

**Comment by ypriverol** [comment]
We are currently using the following ontologies: 
- EFO, everything under https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0000408
- Mondo everything under: https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000001?lang=en
